version: "3.8"
services:
  petclinic:
    build: 
      context: .
    container_name: petclinic_app
    ports:
      - "8081:8080"
    networks:
      - java-net
    environment:
      SPRING_DATABASE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    depends_on:
      - mysql


  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    networks:
      - java-net
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  java-net:

volumes:
  mysql-data:
